images/urls.py
# coding: utf-8
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='image_create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^detail_list/$', views.detail_list, name='detail_list'),
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

images/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Image(models.Model):
    # 制定一个一对多的外键关联。关联名为image_created
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='image_created')
    title = models.CharField(max_length=200)
    # 自动生成的字段
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='image/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    # 对于many to many的关系，django会自动创建一张表，这张表的主键使用
    # 双方主键创建。还有，关于related_name，这是双方都可以使用的
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='image_like',
                                       blank=True)

    def __str__(self):
        return self.title.decode('utf-8')

    def save(self, *args, **kwargs):
        from django.utils.text import slugify
        # 如果没添加slug字段，则自动调用title生成
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('images:detail', args=(self.id, self.slug))
# Create your models here.

images/forms.py
# coding: utf-8
from django import forms
from .models import Image
from urllib import urlopen
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            # 生成一个type = hidden的HTML标签元素，意味着用户看不见
            # 通过widgets字典指定字段的对应HTML标签
            'url': forms.HiddenInput,
        }

    # 在 is_valid()方法调用时执行
    def clean_url(self):
        # 获取表单图片的url
        url = self.cleaned_data['url']
        # 指定合法的图片类型
        valid_extension = ['jpg', 'jpeg']
        # 将url进行分离。分隔符为'.'，最多分离一次。
        # 得到由两个元素的组成的元组，第一个为文件名，第二个是文件类型。
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extension:
            raise forms.ValidationError("The given URL doesn't valid")
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        # 通过指定commit参数为False，生成一个临时的image对象
        image = super(ImageCreateForm, self).save(commit=False)
        # 获取url值
        image_url = self.cleaned_data['url']
        # 生成图片名称
        image_name = "{}.{}".format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())
        # 打开这个图片的url并保存在本地
        response = urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        # 保证在commit参数为True时在保存对象。配合view查看效果更佳。
        if commit:
            image.save()
        # 返回该图片对象。
        return image

images/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST, require_GET
from .forms import ImageCreateForm
from .common.decorators import ajax_required
from actions.utils import create_action


@login_required
def image_create(request):
    """
    通过使用JavaScript创建Image
    :param request:
    :return:
    """
    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, "Image added successful")
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


def detail(request, id, slug):
    from django.shortcuts import get_object_or_404
    from .models import Image
    image = get_object_or_404(Image, id=id, slug=slug)
    users = image.user_like.all()
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image, 'users': users})


@ajax_required
@login_required
@require_POST
def image_like(request):
    import logging
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            from .models import Image
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.user_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.user_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Exception:
            logging.warn('this is a except')
            pass
    return JsonResponse({'status': 'no'})


@require_POST
@ajax_required
@login_required
def detail_list(request):
    image_id = request.POST.get('id')
    if image_id:
        try:
            from .models import Image
            image = Image.objects.get(id=image_id)
            users = image.user_like.all()
            return render(request, 'images/image/detail_list.html', {'users': users})
        except Exception:
            import logging
            logging.warn('this is a error')
            pass
    return render(request, 'images/image/detail_list.html', {'users': None})


@login_required
def image_list(request):
    from .models import Image
    from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
    images = Image.objects.all()
    # 4个一页
    paginator = Paginator(images, 4)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', {'section': 'images', 'images': images})
    return render(request, 'images/image/list.html', {'section': 'images', 'images': images})
# Create your views here.

templates/images/image/create.html
{% extends 'base.html' %}
{% block title %}
Image Create
{% endblock %}
{% block content %}
<h1>Image Create</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="{% url 'images:image_create' %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/images/image/detail.html
{% extends 'base.html' %}
{% block title %}
{{ image.title }}
{% endblock %}
{% block domready %}
    $('a.like').click(
        function(e){
            e.preventDefault();
            var jqxhr = $.post('{% url 'images:like' %}',
                {
                    id: $(this).data('id'),
                    action: $(this).data('action')
                },
                function(data){
                    if (data['status'] == 'ok')
                    {
                        var previous_action = $('a.like').data('action');

                        // toggle data-action
                        $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                        // toggle link text
                        $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                        // update total likes
                        var previous_likes = parseInt($('span.count .total').text());
                        $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                    }
                }
            )
            jqxhr.complete(
            $.post('{% url 'images:detail_list' %}',
                {
                    id: $(this).data('id'),
                },
                function(data){
                    $('#likes').html(data);
                }
            ));
        }
    );
{% endblock %}
{% block content %}
<h1>{{ image.title }}</h1>
    {% load thumbnail %}
    {% thumbnail image.image '300' as im %}
    <a href="{{ image.image.url }}"><img src="{{ im.url }}" alt="No"></a>
    {% endthumbnail %}
    {% with total_count=image.user_like.count users_like=image.user_like.all %}
        <div class="image-info">
            <div>
                <span class="count"><span class="total">{{ total_count }}</span> like{{ total_count|pluralize }}</span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                    {% if request.user not in users_like %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
        </div>
        {{ image.description|linebreaks }}
        <div class="image-likes" id="likes">
            {% include 'images/image/detail_list.html' %}
        </div>
    {% endwith %}
{% endblock %}

templates/images/image/detail_list.html
{% for user in users %}
    <div>
        {% if user.profile.photo %}
            <img src="{{ user.profile.photo.url }}" alt="No">
        {% else %}
            {{ user.first_name }}
        {% endif %}
    </div>
{% empty %}
    Nobody Like This Picture
{% endfor %}

templates/images/image/list.html
{% extends 'base.html' %}

{% block title %}
Images List
{% endblock %}

{% block content %}
<h1>Images bookmarked</h1>
    <div id="image-list">
        {% include 'images/image/list_ajax.html' %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;


    $(window).scroll(
        function()
        {
            var margin = $(document).height() - $(window).height() - 200;
            if ($(window).scrollTop() > margin && !empty_page && !block_request)
            {
                block_request = true;
                page += 1;
                $.get("?page=" + page,
                    function(data)
                    {
                        if (data == "")
                            empty_page = true;
                        else
                        {
                            block_request = false;
                            $("#image-list").append(data);
                        }
                    }
                );
            }
        }
    );
{% endblock %}

templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop='100%' as im %}
            <img src="{{ im.url }}" alt="No">
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
        </div>
    </div>
{% endfor %}