images/urls.py
# coding: utf-8
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='image_create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    url(r'^detail_list/$', views.detail_list, name='detail_list'),
]

social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/css.css' %}" rel="stylesheet">
    </head>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
{#    载入Cookie插件#}
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup(
            {
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain)
                    {
                        xhr.setRequestHeader('X-CSRFToken', csrftoken);
                    }
                }
            }
        );
        $(document).ready(function () {
            {% block domready %}
            {% endblock %}
        })
    </script>
    <body>
        <div id="header">
            <span class="logo">Bookmarks</span>
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li{% if section == 'dashboard' %}
                        class="selected"
                       {% endif %}>
                        <a href="{% url 'dashboard' %}">My Dashboard</a>
                    </li>
                    <li{% if section == 'image' %}
                        class="selected"
                       {% endif %}>
                        <a href="{% url 'images:list' %}">Image</a>
                    </li>
                    <li{% if section == 'people' %}
                        class="selected"
                       {% endif %}>
                        <a href="{% url 'users_list' %}">people</a>
                    </li>
                </ul>
            {% endif %}
            <span class="user">
                {% if request.user.is_authenticated %}
{#                    <img src="/media/{{ request.user.profile.photo }}" alt="有么" height="20" width="20">#}
                    Hello {{ request.user.first_name }}
                    <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </span>
        </div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                    {{ message|safe }}
                        <a href="#" class="close"> </a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>